'on':
  - push

jobs:
  succesful:
    runs-on: ubuntu-22.04
    if: ${{ always() }}
    steps:
      - run: >
          true
      
  failure:
    runs-on: ubuntu-22.04
    if: ${{ always() }}
    steps:
      - run: >
          false
